Repository OBC-HCKTON-GRP03/OneBitHealth, pull requests merged in 2020-12, with the labels that each got.

#28 Force authentication when access exams
  app/controllers/exams_controller.rb
Labels: back-end, bug

#32 Change layout (teste)
  app/views/layouts/application.html.erb
Labels: Feature, front-end

#30 Create CRUD's treatment
  app/assets/stylesheets/treatments.scss
  app/controllers/treatments_controller.rb
  app/helpers/treatments_helper.rb
  app/models/appointment.rb
  app/models/treatment.rb
  app/views/appointments/show.html.erb
  app/views/treatments/_form.html.erb
  app/views/treatments/_treatment.json.jbuilder
  app/views/treatments/edit.html.erb
  app/views/treatments/index.html.erb
  app/views/treatments/index.json.jbuilder
  app/views/treatments/new.html.erb
  app/views/treatments/show.html.erb
  app/views/treatments/show.json.jbuilder
  config/routes.rb
  db/migrate/20201209203820_create_treatments.rb
  db/schema.rb
Labels: Feature, back-end

#34 Fix bug that didn't use destroy dependent
  app/models/user.rb
Labels: back-end, bug

#38 Tests gems and configurations added to project.
  .rspec
  Gemfile
  Gemfile.lock
  config/cucumber.yml
  features/step_definitions/.gitkeep
  features/support/env.rb
  lib/tasks/cucumber.rake
  script/cucumber
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/database_cleaner.rb
  spec/support/devise.rb
  spec/support/shoulda_matchers.rb
Labels: back-end

#48 Feature/applying standard style sign in_and_sign_up
  app/javascript/stylesheets/session_styles.scss
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
Labels: Feature, front-end

#43 Added tests to model User and code to make it pass.
  app/models/user.rb
  spec/models/user_spec.rb
  spec/support/database_cleaner.rb
Labels: back-end, tests

#45 Added tests to model Appointment.
  spec/models/appointment_spec.rb
  spec/support/database_cleaner.rb
Labels: back-end, tests

#56 Insert name to the new users
  db/seeds.rb
Labels: back-end

#58 Insert rubocop-rspec gemfile
  .rubocop.yml
  Gemfile
  Gemfile.lock
Labels: back-end, chore

#61 Tests from Treatment model.
  spec/models/treatment_spec.rb
Labels: back-end, tests

#65 Dashboard bug corrected and controller adjusted to return the user la…
  app/controllers/dashboard_controller.rb
  app/models/user.rb
  app/views/dashboard/index.html.erb
Labels: bug, front-end

#67 Redirect user to dashboard after sign in.
  config/routes.rb
Labels: back-end, enhancement

#68 Sign out link added to top menu bar.
  app/views/shared/_header_dashboard.html.erb
Labels: enhancement, front-end

#70 Feature/page error
  app/controllers/application_controller.rb
  app/controllers/concerns/errors_hanlder.rb
  app/controllers/errors_controller.rb
  app/views/errors/error.html.erb
  config/application.rb
  config/locales/devise.en.yml
  config/locales/en.yml
  config/locales/pt-BR/devise.yml
  config/locales/pt-BR/errors_handler.yml
  config/locales/pt-BR/simple_form.yml
  config/routes.rb
Labels: Feature, front-end

#73 Authentication accpetance tests.
  .rubocop.yml
  Gemfile
  Gemfile.lock
  config/environments/test.rb
  features/authentication.feature
  features/step_definitions/authentication_steps.rb
  features/step_definitions/email_steps.rb
  features/support/env.rb
  spec/factories/users.rb
Labels: front-end, tests

#76 Fix routes
  config/routes.rb
  db/schema.rb
Labels: back-end, bug, chore

#79 Dashboard search.
  app/controllers/dashboard_controller.rb
  app/views/dashboard/_search_results.html.erb
  app/views/dashboard/index.html.erb
  app/views/dashboard/index.js.erb
Labels: Feature, front-end

#83 Add width 100% for sidebar when it is mobile screen
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/menu_sidebar.scss
  app/views/shared/_menu_sidebar.html.erb
Labels: Feature, front-end

#88 Setting the appointment creation view
  app/views/appointments/_form.html.erb
Labels: Feature, front-end

#89 Implementing links in tables,repairing incorrect exam and treatments
  Gemfile.lock
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/dashboard.scss
  app/javascript/stylesheets/globals.scss
  app/views/dashboard/index.html.erb
  app/views/exams/_form.html.erb
Labels: Feature, front-end

#91 route correction
  config/routes.rb
Labels: bug, front-end

#93 Implementação de estilo padrão para as tables e estilização de appointments index
  app/assets/images/delete.svg
  app/assets/images/eye.svg
  app/assets/images/icon_edit.svg
  app/assets/images/icon_show.svg
  app/assets/images/icon_trash.svg
  app/assets/images/pencil.svg
  app/javascript/menu_dashboard.js
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/dashboard.scss
  app/javascript/stylesheets/global_style_tables_consult.scss
  app/views/appointments/index.html.erb
  app/views/layouts/dashboard.html.erb
  app/views/shared/_header_dashboard.html.erb
  app/views/shared/_menu_sidebar.html.erb
Labels: Feature, front-end

#95 Adjusting the partial header.
  app/assets/images/burger_menu.svg
  app/assets/images/icon_arrow_left.svg
  app/assets/images/icon_arrow_right.svg
  app/assets/images/icon_menu_burger.svg
  app/javascript/menu_dashboard.js
  app/javascript/stylesheets/dashboard.scss
  app/views/shared/_header_dashboard.html.erb
Labels: Feature, front-end

#103 Merging all interactive buttons styles into a single file.
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/dashboard.scss
  app/javascript/stylesheets/global_style_tables_consult.scss
  app/javascript/stylesheets/globals.scss
  app/javascript/stylesheets/interactive_button.scss
  app/views/appointments/index.html.erb
  app/views/appointments/show.html.erb
  app/views/layouts/dashboard.html.erb
  app/views/shared/_header_dashboard.html.erb
Labels: Feature, front-end

#102 Link to results details included.
  app/controllers/dashboard_controller.rb
  app/views/dashboard/_search_results.html.erb
Labels: enhancement, front-end

#106 Stylizing appointment page show, card menu has been removed.
  app/javascript/menu_dashboard.js
  app/javascript/stylesheets/global_cards_for_show_view.scss
  app/javascript/stylesheets/globals.scss
  app/javascript/stylesheets/interactive_button.scss
  app/views/appointments/show.html.erb
Labels: Feature, front-end

#104 Appointment form adjusted to portuguese brazilian.
  app/views/appointments/_form.html.erb
  app/views/appointments/edit.html.erb
  app/views/appointments/new.html.erb
Labels: enhancement, front-end

#108 Active record translations.
  config/locales/pt-BR/active-record.yml
Labels: back-end, chore, enhancement

#99 Authentication tests adjusted. Also included how to run the tests in …
  README.md
  features/authentication.feature
  features/step_definitions/authentication_steps.rb
Labels: front-end, tests

#109 Feature/shared users
  app/assets/stylesheets/shared_users.scss
  app/controllers/appointments_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/shared_users_controller.rb
  app/helpers/shared_users_helper.rb
  app/views/appointments/index.html.erb
  app/views/appointments/show.html.erb
  app/views/dashboard/_search_results.html.erb
  app/views/dashboard/users_sharing_with_me.html.erb
  app/views/exams/show.html.erb
  app/views/shared/_menu_sidebar.html.erb
  app/views/shared/_modal_share_history.html.erb
  app/views/shared_users/destroy.html.erb
  app/views/treatments/show.html.erb
  config/routes.rb
  spec/helpers/shared_users_helper_spec.rb
  spec/requests/shared_users_request_spec.rb
  spec/views/shared_users/destroy.html.erb_spec.rb
Labels: Feature, back-end, chore, front-end

#112 Dashboard controller search bug corrected.
  app/controllers/dashboard_controller.rb
Labels: back-end, bug

#113 Upload files to exams
  Gemfile
  Gemfile.lock
  app/controllers/exams_controller.rb
  app/models/exam.rb
  app/uploaders/document_uploader.rb
  app/views/exams/_form.html.erb
  app/views/exams/show.html.erb
  db/migrate/20201213042542_add_documents_to_exams.rb
  db/schema.rb
  public/uploads/exam/documents/1/1_HAROLDO_-_Emissão_Holerite_092020.pdf
  public/uploads/exam/documents/1/_QSD_Apostilao_GitBasico.pdf
Labels: Feature, back-end

#121 Realizada a estilização da pagina de edição e criação de consulta
  app/javascript/stylesheets/global_style_tables_consult.scss
  app/views/appointments/_form.html.erb
  app/views/appointments/edit.html.erb
  app/views/appointments/new.html.erb
Labels: Feature, front-end

#122 Ajustando botão do voltar do form de adicionar consulta
  app/views/appointments/_form.html.erb
Labels: Feature, front-end

#125 Feature/exames styled
  app/views/exams/_form.html.erb
  app/views/exams/index.html.erb
  app/views/exams/new.html.erb
Labels: Feature, front-end

#126 Feature/add styles in treatments forms edit add
  app/controllers/treatments_controller.rb
  app/views/appointments/edit.html.erb
  app/views/appointments/index.html.erb
  app/views/appointments/show.html.erb
  app/views/dashboard/index.html.erb
  app/views/treatments/_form.html.erb
  app/views/treatments/edit.html.erb
  app/views/treatments/index.html.erb
  app/views/treatments/new.html.erb
  app/views/treatments/show.html.erb
Labels: Feature, front-end

#129 Reviewing exam screens making standard stylings and redoing redirects
  app/assets/images/icon_file.svg
  app/controllers/exams_controller.rb
  app/javascript/index.js
  app/javascript/packs/application.js
  app/javascript/packs/menu_dashboard.js
  app/javascript/stylesheets/interactive_button.scss
  app/views/appointments/_form.html.erb
  app/views/appointments/new.html.erb
  app/views/appointments/show.html.erb
  app/views/dashboard/index.html.erb
  app/views/dashboard/index.js.erb
  app/views/exams/_form.html.erb
  app/views/exams/edit.html.erb
  app/views/exams/index.html.erb
  app/views/exams/new.html.erb
  app/views/exams/show.html.erb
  app/views/treatments/_form.html.erb
  app/views/treatments/edit.html.erb
  app/views/treatments/show.html.erb
Labels: Feature, front-end

#136 Readme updated and license created
  LICENSE
  README.md
  app/assets/images/homescreen.png
Labels: documentation, enhancement

#134 Home page adjusted.
  app/assets/images/bg/footer-bg.jpg
  app/assets/images/bg/subscribe-bg.jpg
  app/assets/images/faq/faq-img.jpg
  app/assets/images/logo_inicial_teste.png
  app/assets/images/shapes/shape-1.svg
  app/assets/images/shapes/shape-2.svg
  app/assets/images/shapes/shape-3.svg
  app/assets/images/shapes/shape-4.svg
  app/assets/images/shapes/shape-5.svg
  app/assets/images/shapes/shape-6.svg
  app/assets/images/shapes/shape-7.svg
  app/assets/images/shapes/shape-8.svg
  app/assets/images/slider/slider-1.jpg
  app/assets/images/slider/slider-2.jpg
  app/assets/images/slider/slider-3.jpg
  app/assets/images/we-do/graph-img.svg
  app/assets/images/we-do/we-do-1.svg
  app/assets/images/we-do/we-do-2.svg
  app/assets/images/we-do/we-do-3.svg
  app/assets/images/we-do/we-do-4.svg
  app/assets/javascript/application.js
  app/assets/javascript/main.js
  app/assets/javascript/tiny-slider.js
  app/assets/javascript/wow.min.js
  app/assets/stylesheets/LineIcons.2.0.css
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/bootstrap-5.0.5-alpha.min.css
  app/assets/stylesheets/main.css
  app/assets/stylesheets/main.css.map
  app/views/home/index.html.erb
  app/views/home/index.html.erb.old
  app/views/layouts/home.html.erb
  config/initializers/assets.rb
  public/fonts/LineIcons.eot
  public/fonts/LineIcons.svg
  public/fonts/LineIcons.ttf
  public/fonts/LineIcons.woff
  public/fonts/LineIcons.woff2
Labels: Feature, front-end

#137 Ajustes da página de compartilhar com outro usuário,
  app/assets/images/icon_user.svg
  app/assets/images/icon_user_add.svg
  app/controllers/dashboard_controller.rb
  app/controllers/shared_users_controller.rb
  app/javascript/menu_dashboard.js
  app/javascript/stylesheets/menu_sidebar.scss
  app/views/dashboard/users_sharing_with_me.html.erb
  app/views/shared/_menu_sidebar.html.erb
  app/views/shared_users/destroy.html.erb
  app/views/shared_users/index.html.erb
  config/routes.rb
Labels: Feature, back-end, bug, front-end

#142 add style to return #notice
  app/assets/stylesheets/error.scss
  app/controllers/appointments_controller.rb
Labels: Feature, front-end

#141 File needed to show search results created again.
  app/views/dashboard/index.js.erb
Labels: back-end, bug

#143 Deleted esqueceu seu email form sign in page
  app/views/devise/sessions/new.html.erb
Labels: bug, front-end

#145 Create task to setup the dev env
  Gemfile
  Gemfile.lock
  README.md
  lib/tasks/dev.rake
Labels: back-end, chore

#144 Home page accordion and menu collapse now working.
  app/assets/javascript/application.js
  app/assets/javascript/tiny-slider.js
  app/assets/javascript/wow.min.js
  app/javascript/packs/application.js
  app/javascript/packs/main.js
  app/javascript/packs/sliderConfig.js
  app/views/home/index.html.erb
  app/views/home/index.html.erb.old
  app/views/layouts/home.html.erb
  package.json
  yarn.lock
Labels: bug, front-end

#149 Fix user sharing with me
  app/controllers/appointments_controller.rb
Labels: back-end, bug

#151 Capitalize removed from style.
  app/javascript/stylesheets/global_style_tables_consult.scss
Labels: enhancement, front-end

#152 Modal adjustments
  app/assets/images/icon_search_magnifying_glass.svg
  app/controllers/shared_users_controller.rb
  app/javascript/index.js
  app/javascript/packs/application.js
  app/javascript/shared.js
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/globals.scss
  app/javascript/stylesheets/modal_styles.scss
  app/views/dashboard/_search_results.html.erb
  app/views/shared/_modal_share_history.html.erb
  config/routes.rb
  lib/tasks/dev.rake
Labels: back-end, front-end

#153 Added modal functionality
  app/controllers/shared_users_controller.rb
  app/javascript/shared.js
  app/javascript/stylesheets/globals.scss
  app/javascript/stylesheets/modal_styles.scss
  app/views/shared/_menu_sidebar.html.erb
  app/views/shared/_modal_share_history.html.erb
Labels: Feature, back-end, front-end

#154 New main search field and increment scrollbar
  app/javascript/menu_dashboard.js
  app/javascript/stylesheets/dashboard.scss
  app/javascript/stylesheets/global_style_tables_consult.scss
  app/javascript/stylesheets/menu_sidebar.scss
  app/views/dashboard/_search_results.html.erb
  app/views/dashboard/index.html.erb
  app/views/layouts/dashboard.html.erb
Labels: Feature, front-end

#157 Removing alphabetical order functionality from the modal.
  app/assets/stylesheets/exams.scss
  app/assets/stylesheets/shared_users.scss
  app/assets/stylesheets/treatments.scss
  app/javascript/shared.js
  app/views/shared_users/index.html.erb
Labels: Feature, front-end

#158 Adjusting the appointment tables
  app/javascript/stylesheets/global_style_tables_consult.scss
  app/views/appointments/index.html.erb
  app/views/appointments/show.html.erb
Labels: Feature, front-end

#160 Show messages in Dashboard.
  app/views/dashboard/index.html.erb
Labels: enhancement, front-end

#165 Fix layout Tratment label
  app/views/appointments/show.html.erb
Labels: bug, front-end

#162 Simple form I18n file adjusted.
  app/views/errors/error.html.erb
  config/locales/pt-BR/errors_handler.yml
  config/locales/pt-BR/simple_form.yml
Labels: enhancement, front-end

#167 Rspec tests cleaning and shared users tests.
  spec/helpers/shared_users_helper_spec.rb
  spec/models/shared_user_spec.rb
  spec/models/treatment_spec.rb
  spec/requests/shared_users_request_spec.rb
  spec/views/shared_users/destroy.html.erb_spec.rb
Labels: back-end, tests
